// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  notesSidebar: [
    {
      type: 'category',
      label: '深度筆記',
      collapsible: true,   // 可折疊
      collapsed: false,    // 預設展開
      items: [
        {
          type: 'autogenerated',
          dirName: '.',     // 讀取 docs 整個資料夾
        },
      ],
    },
  ],
};

export default sidebars;

